### ISSUE TITLE
`core` might confuse proc macros

### ISSUE THREAD

**Issue by toyboot4e** [LechintanTudor/anchor#1]
Hi 👋 It’s super nice to see a new work of yours!

I’m here to just mention the potential issue. Some user might import `anchor::core` and it can override the prelude’s `core` crate (https://doc.rust-lang.org/core/). Proc macros often use `::core` so it can cause unfamiliar errors. I like the word `core` though 🤨 Going with `mod core` is still cool.

**Comment by LechintanTudor** [comment]
Hi! 🙂

I forgot about the `core` crate; definitely wouldn't want to have name conflicts with it. I'm thinking about changing the module name to `game` as it mostly contains functionality related to the game loop. 🤔

**Comment by toyboot4e** [comment]
Hi it was misinformation. Sorry. The following code worked without any issue:

```rust
use anchor::core;

struct HelloWorld;

impl ::core::fmt::Debug for HelloWorld {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        write!(f, "Hello, world!")
    }
}

fn main() {
    println!("{:?}", HelloWorld);
}
```

https://github.com/toyboot4e/core_does_not_conflict/blob/main/src/main.rs

Maybe the last proc macro I saw was using `core`, not `::core`?

**Comment by LechintanTudor** [comment]
Ended up changing the name to `game`. Although it wouldn't necessarily cause issues with proc macros, it makes importing items from the `core` crate more difficult, e.g. `use ::core::num::NonZeroU8;` instead of `use core::num::NonZeroU8;`.
